### ISSUE TITLE
Unable to perform a followup action in custom action

### ISSUE THREAD

**Issue by Wing-e7** [RasaHQ/rasa-sdk#175]
**Rasa version**: 1.9.6

**Python version**: 3.7

**Operating system** Win 10

**Issue**:  Unable to force the next action. Tried trigger_followup_action. Getting errors in the same as well.  Also tried tracker.followup_action("utter_getout")
tracker.followup_action(utter_getout)
Tried both by defining an object f = tracker.followup_action

Nothing works..! 

**Error (including full traceback)**:
```
(base) C:\Users\Collegedunia\Documents\rasaINIT>rasa run actions --debug
2020-04-18 22:05:26 INFO     rasa_sdk.endpoint  - Starting action endpoint server...
2020-04-18 22:05:27 INFO     rasa_sdk.executor  - Registered function for 'action_ggf'.
2020-04-18 22:05:27 INFO     rasa_sdk.executor  - Registered function for 'action_customsentiment'.
2020-04-18 22:05:27 DEBUG    rasa_sdk.utils  - Using the default number of Sanic workers (1).
2020-04-18 22:13:59 DEBUG    rasa_sdk.executor  - Received request to run 'action_customsentiment'
Exception occurred while handling uri: 'http://localhost:5055/webhook'
Traceback (most recent call last):
  File "c:\users\collegedunia\anaconda3\lib\site-packages\sanic\app.py", line 976, in handle_request
    response = await response
  File "c:\users\collegedunia\anaconda3\lib\site-packages\rasa_sdk\endpoint.py", line 86, in webhook
    result = await executor.run(action_call)
  File "c:\users\collegedunia\anaconda3\lib\site-packages\rasa_sdk\executor.py", line 283, in run
    events = action(dispatcher, tracker, domain)
  File "C:\Users\Collegedunia\Documents\rasaINIT\actions.py", line 48, in run
    f(utter_getout)
NameError: name 'utter_getout' is not defined
```

**Command or request that led to error**:
```
rasa interactive --endpoints endpoints.yml --debug
```

**Content of domain file (domain.yml)** (if relevant):
```
actions:
- action_customsentiment
- action_ggf
- utter_affirm
- utter_cbacklater
- utter_cheer_up
- utter_did_that_help
- utter_getout
- utter_goodbye
- utter_greet
- utter_happy
- utter_iamabot
- utter_ilike
entities:
- admission
- company
- hurray
- products
- traffic
intents:
- greet
- pitch
- mood_great
- goodbye
- affirm
- deny
- mood_unhappy
- bot_challenge
responses:
  utter_affirm:
  - text: okay
  utter_cbacklater:
  - text: You should come back later
  utter_cheer_up:
  - image: https://i.imgur.com/nGF1K8f.jpg
    text: 'Here is something to cheer you up:'
  utter_did_that_help:
  - text: Did that help you?
  utter_getout:
  - text: Get out of my face !
  utter_goodbye:
  - text: Bye
  utter_greet:
  - text: Hey! How are you?
  utter_happy:
  - text: Great, carry on!
  utter_iamabot:
  - text: I am a bot, powered by Rasa.
  utter_ilike:
  - text: Wonderful !! Give me more .
session_config:
  carry_over_slots_to_new_session: true
  session_expiration_time: 60

```

**Contents of actions.py** (if  relevant):
```python
from typing import Any, Text, Dict, List

from rasa_sdk import Action, Tracker
from rasa.core.trackers import DialogueStateTracker
from rasa_sdk.executor import CollectingDispatcher
import nltk
from nltk.sentiment.vader import SentimentIntensityAnalyzer
import os
import pymysql
import mysql.connector
import pandas as pd
import json 


class Actionggf(Action):

    def name(self) -> Text:
        return "action_ggf"

    def run(self, dispatcher: CollectingDispatcher,
             tracker: Tracker,
             domain: Dict[Text, Any]) -> List[Dict[Text, Any]]:

        dispatcher.utter_message(text="Hello World GGF MMH!")

        return []

class ActionCustomSentiment(Action):

    def name(self) -> Text:
        return "action_customsentiment"

    def run(self, dispatcher: CollectingDispatcher,
             tracker: Tracker,
             domain: Dict[Text, Any]) -> List[Dict[Text, Any]]:

        f = tracker.followup_action
        #tracker.trigger_follow_up_action(action_utter_getout)
        f(utter_getout)
        #dispatcher.utter_message('GF JJYHUUGHJHJHJGH') 
        return []

```

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @rgstephens will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗
