### ISSUE TITLE
Rasa actions server not starting: No module named 'actions'

### ISSUE THREAD

**Issue by RishiGondkar** [RasaHQ/rasa-sdk#310]
**Rasa version**:1.6.1

**Rasa SDK version**:1.6.1

**Python version**:3.6.9

**Operating system** (windows, osx, ...):

**Issue**: Rasa actions server not starting

**Error (including full traceback)**:
```
robolab@robolab:~/robocomp/components/robocomp-viriato/components/conversationalAgent$ rasa run actions
2020-10-19 12:55:01 INFO     rasa_sdk.endpoint  - Starting action endpoint server...
2020-10-19 12:55:01 ERROR    rasa_sdk.executor  - Failed to register package 'actions'.
Traceback (most recent call last):
  File "/home/robolab/.local/lib/python3.6/site-packages/rasa_sdk/executor.py", line 206, in register_package
    self._import_submodules(package)
  File "/home/robolab/.local/lib/python3.6/site-packages/rasa_sdk/executor.py", line 191, in _import_submodules
    package = importlib.import_module(package)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'actions'
Unable to start server
Traceback (most recent call last):
  File "/home/robolab/.local/lib/python3.6/site-packages/sanic/server.py", line 860, in serve
    http_server = loop.run_until_complete(server_coroutine)
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1727, in create_server
```

**Command or request that led to error**:
```
rasa run actions
```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Contents of actions.py** (if  relevant):
```python

```

**Comment by sara-tagger** [comment]
Thanks for the issue, @akelad will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by akelad** [comment]
@RishiGondkar what does your directory structure look like?

**Comment by RishiGondkar** [comment]
Can you explain what exactly do you want for the directory structure?

**Comment by akelad** [comment]
the contents of your directory `conversationalAgent`, where you're starting the action server from. by default it will load up a file named `actions.py`

**Comment by RishiGondkar** [comment]
Yes there is actions.py present in the folder. Folder contents:

actions.py       domin_with_genders.yml  person_attributes.json
config.yml       endpoints.yml           __pycache__
credentials.yml  graph.html              rasa_conversation.json
data             __init__.py             results
domain.yml       models                  story_graph.dot

**Comment by akelad** [comment]
can you try moving that file into a folder called `actions`? which contains an `__init__.py` and your `actions.py`. i think by default the rasa sdk assumes it's in that folder
