### ISSUE TITLE
Retrieving all sessions with end-to-end story retrieval endpoints always returns an error

### ISSUE THREAD

**Issue by nbeuchat** [RasaHQ/rasa-sdk#388]
**Rasa version**: 2.2.1

**Rasa SDK version**: 2.2.0

**Python version**: 3.7.9

**Operating system** (windows, osx, ...): 

**Issue**:
When trying to use _Retrieve an end-to-end story corresponding to a conversation_ endpoint with `all_sessions=true`, I always get an error. 

**Error (including full traceback)**:
The error I get back from the Rest API call
```
{
    "version": "2.2.1",
    "status": "failure",
    "message": "An unexpected error occurred. Error: 'str' object has no attribute 'name'",
    "reason": "ConversationError",
    "details": {},
    "help": null,
    "code": 500
}
```

And the action server error:
```
2021-01-05 12:10:56 DEBUG    rasa.core.tracker_store  - sender_id=2373134909417533 Recreating tracker for id '2373134909417533'
2021-01-05 12:10:56 DEBUG    rasa.server  - sender_id=2373134909417533 Traceback (most recent call last):
  File "/home/nicolas/anaconda3/envs/chatbot2.0/lib/python3.7/site-packages/rasa/server.py", line 805, in retrieve_story
    fetch_all_sessions=fetch_all_sessions,
  File "/home/nicolas/anaconda3/envs/chatbot2.0/lib/python3.7/site-packages/rasa/server.py", line 275, in get_test_stories
    trackers = processor.get_trackers_for_all_conversation_sessions(conversation_id)
  File "/home/nicolas/anaconda3/envs/chatbot2.0/lib/python3.7/site-packages/rasa/core/processor.py", line 287, in get_trackers_for_all_conversation_sessions
    return rasa.shared.core.trackers.get_trackers_for_conversation_sessions(tracker)
  File "/home/nicolas/anaconda3/envs/chatbot2.0/lib/python3.7/site-packages/rasa/shared/core/trackers.py", line 912, in get_trackers_for_conversation_sessions
    for evts in split_conversations
  File "/home/nicolas/anaconda3/envs/chatbot2.0/lib/python3.7/site-packages/rasa/shared/core/trackers.py", line 912, in <listcomp>
    for evts in split_conversations
  File "/home/nicolas/anaconda3/envs/chatbot2.0/lib/python3.7/site-packages/rasa/shared/core/trackers.py", line 156, in from_events
    tracker = cls(sender_id, slots, max_event_history, sender_source)
  File "/home/nicolas/anaconda3/envs/chatbot2.0/lib/python3.7/site-packages/rasa/shared/core/trackers.py", line 185, in __init__
    self.slots = {slot.name: copy.copy(slot) for slot in slots}
  File "/home/nicolas/anaconda3/envs/chatbot2.0/lib/python3.7/site-packages/rasa/shared/core/trackers.py", line 185, in <dictcomp>
    self.slots = {slot.name: copy.copy(slot) for slot in slots}
AttributeError: 'str' object has no attribute 'name'

2021-01-05 12:10:56 ERROR    rasa.server  - sender_id=2373134909417533 An unexpected error occurred. Error: 'str' object has no attribute 'name'
```

**Command or request that led to error**:
```
GET http://localhost:5005/conversations/2373134909417533/story?token=xxxxx&all_sessions=true
```

**Comment by nbeuchat** [comment]
I dug a bit deeper and when I call the endpoint for a sender_id with two sessions, the line `self.slots = {slot.name: copy.copy(slot) for slot in slots}` in the `trackers.py` is causing issue. The init function is called twice:

The first time the tracker initializer is called, `slots` is (correctly) set to: 
```
>>> slots
[<BooleanSlot(apt_interested: None)>, <BooleanSlot(apt_interested_confirmed: None)>, ...]
```

The second time it calls this function, `slots` has a different structure which leads to the error mentioned in the issue:
```
>>> slots
{'apt_interested': <BooleanSlot(apt_interested: None)>, 'apt_interested_confirmed': <BooleanSlot(apt_interested_confirmed: None)>, 'apt_lease_length_fits': <BooleanSlot(apt_lease_length_fits: None)>, ...}
```

**Comment by sara-tagger** [comment]
Thanks for the issue, @rctatman will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗
