### ISSUE TITLE
ModuleNotFoundError: No module named 'typing_extensions'

### ISSUE THREAD

**Issue by mtenkoppel** [RasaHQ/rasa-sdk#395]
**Rasa version**: 2.2.5

**Rasa SDK version**: 2.2.0

**Python version**: 3.8.6

**Operating system** (windows, osx, ...): /Users/Maurice/opt/anaconda3/envs/tut1/bin/python3.8

**Issue**: I followed the tutorial on form validation from the [docs](https://rasa.com/docs/rasa/next/forms). I ran the code and ran into an issue that TypedDict was not available.

This can be resolved by running pip install typing-extensions. So I guess it is somewhere not mentioned as dependency.

**Error (including full traceback)**:
```
Traceback (most recent call last):
  File "/Users/Maurice/opt/anaconda3/envs/tut1/lib/python3.8/site-packages/rasa_sdk/executor.py", line 254, in register_package
    self._import_submodules(package)
  File "/Users/Maurice/opt/anaconda3/envs/tut1/lib/python3.8/site-packages/rasa_sdk/executor.py", line 217, in _import_submodules
    self._import_module(full_name)
  File "/Users/Maurice/opt/anaconda3/envs/tut1/lib/python3.8/site-packages/rasa_sdk/executor.py", line 231, in _import_module
    module = importlib.import_module(name)
  File "/Users/Maurice/opt/anaconda3/envs/tut1/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/Maurice/Library/Mobile Documents/com~apple~CloudDocs/00MAI/01Classes/Project AI use case/code/tut1/actions/actions.py", line 18, in <module>
    from rasa_sdk.types import DomainDict
  File "/Users/Maurice/opt/anaconda3/envs/tut1/lib/python3.8/site-packages/rasa_sdk/types.py", line 3, in <module>
    from typing_extensions import TypedDict
ModuleNotFoundError: No module named 'typing_extensions'

```

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @melindaloubser1 will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by melindaloubser1** [comment]
Looks like this is specific to python > 3.8 - see https://pypi.org/project/typing-extensions/ . @alwx something to add to dependencies?

**Comment by LoveMeWithoutAll** [comment]
I got a same error!

**Comment by AlperKaan35** [comment]
I am getting the same error. Please fix this. Any workarounds?

**Comment by melindaloubser1** [comment]
You can use a python 3.7 virtual env, that will definitely work. 
Also, from the original poster
```
This can be resolved by running pip install typing-extensions.
```

**Comment by rajhlinux** [comment]
The solution provided from:
[melindaloubser1](https://github.com/melindaloubser1)

Did the trick for me:

`pip install typing-extensions
`

I am using FreeBSD 13.1.
