### ISSUE TITLE
M1 Silicon Chipset Build -> Install error

### ISSUE THREAD

**Issue by sbilgil** [RasaHQ/rasa-sdk#867]
**Rasa version**:
2.0
**Rasa SDK version**:
2.8
**Python version**:
3.7.9
**Operating system** (windows, osx, ...):
MacOs 12.3 Silicon M1 Chipset
**Issue**:
I have the codebase from version 2 and i was using and making some changes to code itself. When i make change i need to build it from my source code. After changing my computer to M1 Chipset Mac (ex was Intel chipset Mac) i couldnt build RASA codes. I followed internet tips and i hardly managed to build it. Then i tried to follow instructions on RASA Readme and it told me to use python 3.7.9 to create environment. I did it. And i tried to build my rasa-sdk codebase and i start to get en error (when i used 3.8 i didnt get error before)

**Error (including full traceback)**:
```
Collecting multidict<6.0,>=5.0
  Using cached multidict-5.2.0.tar.gz (49 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [71 lines of output]
      *********************
      * Accelerated build *
      *********************
      running dist_info
      creating /private/var/folders/3r/lscxbw557b37671_q_xn6d300000gp/T/pip-modern-metadata-jjnjivyn/multidict.egg-info
      writing /private/var/folders/3r/lscxbw557b37671_q_xn6d300000gp/T/pip-modern-metadata-jjnjivyn/multidict.egg-info/PKG-INFO
      writing dependency_links to /private/var/folders/3r/lscxbw557b37671_q_xn6d300000gp/T/pip-modern-metadata-jjnjivyn/multidict.egg-info/dependency_links.txt
      writing top-level names to /private/var/folders/3r/lscxbw557b37671_q_xn6d300000gp/T/pip-modern-metadata-jjnjivyn/multidict.egg-info/top_level.txt
      writing manifest file '/private/var/folders/3r/lscxbw557b37671_q_xn6d300000gp/T/pip-modern-metadata-jjnjivyn/multidict.egg-info/SOURCES.txt'
      reading manifest file '/private/var/folders/3r/lscxbw557b37671_q_xn6d300000gp/T/pip-modern-metadata-jjnjivyn/multidict.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no previously-included files matching '*.pyc' found anywhere in distribution
      warning: no previously-included files found matching 'multidict/_multidict.html'
      warning: no previously-included files found matching 'multidict/*.so'
      warning: no previously-included files found matching 'multidict/*.pyd'
      warning: no previously-included files found matching 'multidict/*.pyd'
      no previously-included directories found matching 'docs/_build'
      adding license file 'LICENSE'
      writing manifest file '/private/var/folders/3r/lscxbw557b37671_q_xn6d300000gp/T/pip-modern-metadata-jjnjivyn/multidict.egg-info/SOURCES.txt'
      creating '/private/var/folders/3r/lscxbw557b37671_q_xn6d300000gp/T/pip-modern-metadata-jjnjivyn/multidict-5.2.0.dist-info'
      Traceback (most recent call last):
        File "/Users/sadikalperbilgil/Documents/NLP/sofieNLPVersions/envNLPV2arm/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/Users/sadikalperbilgil/Documents/NLP/sofieNLPVersions/envNLPV2arm/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/sadikalperbilgil/Documents/NLP/sofieNLPVersions/envNLPV2arm/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 164, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/private/var/folders/3r/lscxbw557b37671_q_xn6d300000gp/T/pip-build-env-hslhodjv/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 377, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/private/var/folders/3r/lscxbw557b37671_q_xn6d300000gp/T/pip-build-env-hslhodjv/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 483, in run_setup
          self).run_setup(setup_script=setup_script)
        File "/private/var/folders/3r/lscxbw557b37671_q_xn6d300000gp/T/pip-build-env-hslhodjv/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 92, in <module>
        File "/private/var/folders/3r/lscxbw557b37671_q_xn6d300000gp/T/pip-build-env-hslhodjv/overlay/lib/python3.7/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/private/var/folders/3r/lscxbw557b37671_q_xn6d300000gp/T/pip-build-env-hslhodjv/overlay/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/private/var/folders/3r/lscxbw557b37671_q_xn6d300000gp/T/pip-build-env-hslhodjv/overlay/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/private/var/folders/3r/lscxbw557b37671_q_xn6d300000gp/T/pip-build-env-hslhodjv/overlay/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 968, in run_commands
          self.run_command(cmd)
        File "/private/var/folders/3r/lscxbw557b37671_q_xn6d300000gp/T/pip-build-env-hslhodjv/overlay/lib/python3.7/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/private/var/folders/3r/lscxbw557b37671_q_xn6d300000gp/T/pip-build-env-hslhodjv/overlay/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.run()
        File "/private/var/folders/3r/lscxbw557b37671_q_xn6d300000gp/T/pip-build-env-hslhodjv/overlay/lib/python3.7/site-packages/setuptools/command/dist_info.py", line 101, in run
          bdist_wheel = self.get_finalized_command('bdist_wheel')
        File "/private/var/folders/3r/lscxbw557b37671_q_xn6d300000gp/T/pip-build-env-hslhodjv/overlay/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 305, in get_finalized_command
          cmd_obj = self.distribution.get_command_obj(command, create)
        File "/private/var/folders/3r/lscxbw557b37671_q_xn6d300000gp/T/pip-build-env-hslhodjv/overlay/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 859, in get_command_obj
          klass = self.get_command_class(command)
        File "/private/var/folders/3r/lscxbw557b37671_q_xn6d300000gp/T/pip-build-env-hslhodjv/overlay/lib/python3.7/site-packages/setuptools/dist.py", line 954, in get_command_class
          self.cmdclass[command] = cmdclass = ep.load()
        File "/private/var/folders/3r/lscxbw557b37671_q_xn6d300000gp/T/pip-build-env-hslhodjv/overlay/lib/python3.7/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 194, in load
          module = import_module(match.group('module'))
        File "/Users/sadikalperbilgil/.pyenv/versions/3.7.9/lib/python3.7/importlib/__init__.py", line 127, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
        File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
        File "<frozen importlib._bootstrap>", line 983, in _find_and_load
        File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 728, in exec_module
        File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
        File "/private/var/folders/3r/lscxbw557b37671_q_xn6d300000gp/T/pip-build-env-hslhodjv/overlay/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 26, in <module>
          from .macosx_libfile import calculate_macosx_platform_tag
        File "/private/var/folders/3r/lscxbw557b37671_q_xn6d300000gp/T/pip-build-env-hslhodjv/overlay/lib/python3.7/site-packages/wheel/macosx_libfile.py", line 41, in <module>
          import ctypes
        File "/Users/sadikalperbilgil/.pyenv/versions/3.7.9/lib/python3.7/ctypes/__init__.py", line 7, in <module>
          from _ctypes import Union, Structure, Array
      ModuleNotFoundError: No module named '_ctypes'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Command or request that led to error**:
```
pip install rasa_sdk-2.8.2-py3-none-any.whl
```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Contents of actions.py** (if  relevant):
```python

```

**Comment by sbilgil** [comment]
I am changing the codebase. So i am using my own build for sdk. And also this is not from sdk part
