### ISSUE TITLE
'Namespace' object has no attribute 'logging_config_file'

### ISSUE THREAD

**Issue by mill1983** [RasaHQ/rasa-sdk#963]
`rasa run actions`
The following error has occurred:
```
Traceback (most recent call last):
  File "/opt/venv/bin/rasa", line 8, in <module>
    sys.exit(main())
  File "/opt/venv/lib/python3.8/site-packages/rasa/__main__.py", line 125, in main
    cmdline_arguments.func(cmdline_arguments)
  File "/opt/venv/lib/python3.8/site-packages/rasa/cli/run.py", line 57, in run_actions
    sdk.main_from_args(args)
  File "/opt/venv/lib/python3.8/site-packages/rasa_sdk/__main__.py", line 17, in main_from_args
    args.logging_config_file,
AttributeError: 'Namespace' object has no attribute 'logging_config_file'
```

`rasa run actions -h` Display, the parameter `--logging_config_file` is not supported

```
Python Logging Options:
  You can control level of log messages printed. In addition to these arguments, a more fine grained configuration can be achieved with environment variables. See online documentation for more info.

  -v, --verbose         Be verbose. Sets logging level to INFO. (default: None)
  -vv, --debug          Print lots of debugging statements. Sets logging level to DEBUG. (default: None)
  --quiet               Be quiet! Sets logging level to WARNING. (default: None)

```

**Comment by Vivekt719** [comment]
One possible reason for this error is that the rasa_sdk package is not up to date, as this issue was fixed in a recent version of the package. I suggest checking if there is a new version of rasa_sdk available and updating to it if necessary.

**Comment by hsm207** [comment]
@mill1983 run the action server with `python -m rasa_sdk` instead
